networks:
  server:
    driver: bridge

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./app/:/var/www/
      - ./nginx/:/etc/nginx/conf.d/
      - ./log/nginx/:/var/log/nginx/
    networks:
      - server

  php:
    container_name: php
    build: ./php/
    volumes:
      - ./app/:/var/www/
    networks:
      - server

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - server

volumes:
  db_volume:
    driver: local
